build-game:
   stage: build
   script:
      - make cardGame
   artifacts:
      paths:
         - cardGame

build-test:
   stage: build
   script:
      - make testGame
   artifacts:
      paths:
         - testGame

test:
   stage: test
   script:
      - make tests

staticAnalysis:
   stage: test
   script:
      - make static
      
style:
   stage: test
   script:
      - make style

coverage:
   stage: test
   script:
      - make coverage
   artifacts:
      paths:
         - coverage
      expire_in: 14 days

memoryLeaks:
   stage: test
   script:
      - make fullmemcheck

docs:
   stage: deploy
   script:
      - make docs
   artifacts:
      paths:
         - docs
      expire_in: 14 days
